version: '3.1'

services:
  wiremock:
    container_name: stub
    image: wiremock/wiremock:3.3.1
    networks:
      - api-testing

  api:
    container_name: service
    build: .
    depends_on:
      - wiremock
    volumes:
      - /home/aleksei/Downloads/docker/:/service/build/reports/
    networks:
      - api-testing
    env_file:
      - .env

networks:
  api-testing:
    driver: bridge