version: '3.1'

services:
  banking:
    container_name: banking-service
    build: .
    networks:
      - banking
    environment:
      - ATC_SERVICE_URL=https://api.police.gov
    ports:
      - "8080:8080"

networks:
  banking:
    driver: bridge