version: '3.1'

services:
  bank-api:
    build: .
    command: ["java", "-jar", "service/build/libs/service-1.0-SNAPSHOT.jar"]
    env_file:
      - .env

  tests:
    build: .
    command: ["./gradlew", "test"]
    env_file:
      - .env
    volumes:
      - ./reports/:/src/testing/build/reports/
    depends_on:
      - bank-api
