FROM gradle:jdk17-alpine
WORKDIR /src

COPY ./gradle ./gradle
COPY ./testing ./testing
COPY ./build.gradle ./build.gradle
COPY ./settings.gradle ./settings.gradle
COPY ./gradlew ./gradlew

ARG ATC_SERVICE_URL
ENV ATC_SERVICE_URL=$ATC_SERVICE_URL

RUN ./gradlew :testing:build -x test
CMD ./gradlew test